name: build
on:
  push: null
jobs:
  build-unix:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        type:
          - Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: appimage
          submodules: recursive
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-z64re-ccache-${{ matrix.type }}
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: >
          sudo apt-get update && sudo apt install -y ninja-build libgtk-3-dev lld
          llvm clang-15 libfreetype-dev libfuse2 libsdl2-dev gcc-mips-linux-gnu
          binutils-mips-linux-gnu python3-pip python3-venv libpng-dev
      - name: Install SDL2 Dependencies
        if: runner.os == 'Linux'
        run: |
          # Install SDL2
          echo ::group::install SDL2

          # Enable ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          SDLVER=2.26.1
          if [[ ! -e ~/.ccache ]]; then
              mkdir ~/.ccache
          fi
          cd ~/.ccache 
          if [[ ! -e SDL2-${SDLVER} ]]; then
          	curl -sSLO https://libsdl.org/release/SDL2-${SDLVER}.tar.gz
          	tar -xzf SDL2-${SDLVER}.tar.gz
          	cd SDL2-${SDLVER}
              ./configure
              make -j8 && cd ../
              rm SDL2-${SDLVER}.tar.gz
          fi
          sudo make -C SDL2-${SDLVER} install
          sudo cp -av /usr/local/lib/libSDL* /lib/x86_64-linux-gnu/
          echo ::endgroup::
      - name: Clone DrMario_decomp
        run: |
          git clone https://github.com/AngheloAlf/drmario64 drmario64_decomp
          cd drmario64_decomp
          # Enable ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          if [[ ! -e ~/.ccache/baserom.us.z64 ]]; then
              curl -sSfL ${{ secrets.BASEROM }} -o ~/.ccache/baserom.us.z64
              md5sum baserom.us.z64
          fi
          ls ~/.ccache
          cp ~/.ccache/baserom.us.z64 .
          #python3 -m pip install --no-cache-dir -r requirements.txt
          #cargo install pigment64 --version ">=0.3.0,<1.*"
          #make setup && make lib && make extract && make
          #cp build/us/drmario64_uncompressed.us.z64 ..
          #cp build/us/drmario64.us.elf ..
